### ISSUE TITLE
Product catalogue

### ISSUE THREAD

**Issue by michal-kwiatkowski** [michal-kwiatkowski/test-repo-1#2]
### Product Detail Page / Accessing product information

As a merchant I want to be able to:

- [ ]  create product details page containing all product related information available from the ecommerce backend (need to have access to all properties and all variants of the product)

As user I want to:

- [ ]  see the default variant of the product when I open product details page
- [ ]  see all the product information on PDP as designed in the template
- [ ]  be able to switch between product variants on PDP - the relevant variant related product information should be updated when variant is being changed (image, price, size etc.)

### Product Listing Page / Accessing category information

As a merchant I want to:

- [ ]  be able to create category tree and allow users to navigate based on it
- [ ]  be able to present the product listing page containing products from selected category

As user I want to:

- [ ]  see all the relevant information on the PLP/category page as defined in the template (eg. product name, image, price, average review rate etc.)
- [ ]  have the PLP paginated
- [ ]  be able to navigate to PDP when clicked on a particular product
- [ ]  be able to filter products displayed on PLP based on selected attributes
- [ ]  sort the PLP based on selected criteria (name asc/desc, price asc/desc etc.)
- [ ]  display the PLP as a product grid or as a list
- [ ]  see the breadcrumb reflecting the navigation I took to reach the particular page (subcategory etc) and have the option to go back to the higher level PLP I visited during the navigation
- [ ]  be able to search for products using the default search option provided by the commerce backend platform (eg. projection search)
- [ ]  be able to display reviews of the product
- [ ]  be able to add a review of the product
